---
title: "script"
author: "Dariush"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Reading datasets
#Cosmetix Expenditure in 1399
data1 <- read.csv("C:\\Users\\dghasemisemeskandeh\\Desktop\\NewData1.csv", header = TRUE, stringsAsFactors = FALSE, colClasses = )

#Families general information
data2 <- read.csv("C:\\Users\\dghasemisemeskandeh\\Desktop\\NewData2.csv", header = TRUE, stringsAsFactors = FALSE)

#Families peoperties and utensiles
data3 <- read.csv("C:\\Users\\dghasemisemeskandeh\\Desktop\\NewData3.csv", header = TRUE, stringsAsFactors = FALSE)
```

```{r}


colnames(data1)[names(data1) == "ï..Category1"] <- "Category1"
colnames(data2)[names(data2) == "ï..Category2"] <- "Category2"
colnames(data3)[names(data3) == "ï..Category3"] <- "Category3"

data1$Address <- as.character(data1$Address)
data2$Address <- as.character(data2$Address)
data3$Address <- as.character(data3$Address)

```


```{r}
#finding ununique families' ID in different datasets
setdiff(data1$Address[1:10], data2$Address[1:10])
```

```{r}
#Number of unique observations in each datasets

#Cosmetics1 = 31,942
#data1 = 31,942
#data2 = 37,520
#data3 = 37,557

length(unique(data2$Address))
```

```{r}
head(data1)
```
```{r}
data1 %>% count(CosmeticCode)

data1_prep <- data1 %>%
  group_by(Address) %>% 
  summarise(SumCosExp = sum(CosmeticExpenditure))
```

```{r}
library(tidyverse)

#length(unique(data2[data2$FamilyMemberN > 6, "Address"]))
#[1] 901

data2_prep <- data2 %>% 
  filter(FamilyMemberN < 7) %>%
  pivot_wider(id_cols = c(Category2, Address), 
                                    names_from = FamilyMemberN,
                                    values_from = c(Dependency, Sex, Age, Eduaction, StillEduacating,                                                          Degree, OccupationStatus, MaritalStatus)) #names_glue = "{pheno}_{.value}"
head(data2_prep)
```
```{r}
#dataset for clustering
merge(data1[,c("Category1", "Address")], data1_prep, by = "Address",  all.y = FALSE) %>% glimpse()

cosdata <- merge(data2_prep, data1_prep, by = "Address")
```

```{r , echo=TRUE}
Cosmetics2 %>%
  mutate(Gender = ifelse(Sex == 1, "Male", "Female")) %>%
  ggplot(aes(Gender, CosmeticExpenditure)) +
  #geom_point(aes(color = Gender), alpha = 0.2)
  geom_boxplot()+ theme_classic()
  

```

```{r}
library(pheatmap)

cosdata %>% glimpse()
cosdata %>% count(Category2)

pheatmap(cor(cosdata[, -c(1:2)]))
```

str(cosdata)





